#ifndef SYSTEM_CONFIG
#define SYSTEM_CONFIG

#define MONITOR_CAPACITY 256
#define SYSTEM_OFFSET 0x80000000
#define MONITORING_RESOLUTION 1000

#define REBALANCE_THRESHOLD 1

#define DO_REBALANCING
// #define DO_MONITORING

#endif